developer:
  dev-mode: true
  rewards-enabled: true
  id-pattern: "####"

game:
  knockbackStick: false
  max: 40
  min: 4
  defaultTimer: 30
  duelEndY: 69
  cooldown-notify:
    - 30
    - 15
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1